"""Convert tuned PID parameters to C code for embedding in MCU firmware.

Usage:
  python scripts/convert_to_code.py --loop speed
  python scripts/convert_to_code.py --all
"""

from __future__ import annotations

import argparse
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).parent.parent))

from core.config import load_config


C_TEMPLATE = """\
// Auto-generated PID parameters for {loop_name} ({loop_display_name})
// Generated by PID Auto-Tuner
// Description: {description}

#define {PREFIX}_KP  {kp:.6f}f
#define {PREFIX}_KI  {ki:.6f}f
#define {PREFIX}_KD  {kd:.6f}f
"""

C_STRUCT_TEMPLATE = """\
// Auto-generated PID parameters struct
// Generated by PID Auto-Tuner

typedef struct {{
    float kp;
    float ki;
    float kd;
}} PID_Params_t;

{structs}
"""


def main() -> None:
    parser = argparse.ArgumentParser(description="Convert PID params to C code")
    parser.add_argument("--loop", "-l", help="Loop name")
    parser.add_argument("--all", action="store_true", help="Export all loops")
    parser.add_argument("--format", choices=["define", "struct"], default="define")
    parser.add_argument("--output", "-o", help="Output file path")
    parser.add_argument("--config", help="Config file path")
    args = parser.parse_args()

    config = load_config(args.config)

    if args.all:
        loops = list(config.loops.keys())
    elif args.loop:
        loops = [args.loop]
    else:
        print("Specify --loop <name> or --all")
        return

    output_lines: list[str] = []

    if args.format == "struct":
        structs = []
        for loop_name in loops:
            loop = config.get_loop(loop_name)
            prefix = loop_name.upper()
            structs.append(
                f"const PID_Params_t {prefix}_PID = {{\n"
                f"    .kp = {loop.pid.kp:.6f}f,\n"
                f"    .ki = {loop.pid.ki:.6f}f,\n"
                f"    .kd = {loop.pid.kd:.6f}f,\n"
                f"}};"
            )
        code = C_STRUCT_TEMPLATE.format(structs="\n\n".join(structs))
    else:
        parts = []
        for loop_name in loops:
            loop = config.get_loop(loop_name)
            parts.append(C_TEMPLATE.format(
                loop_name=loop_name,
                loop_display_name=loop.name,
                description=loop.description,
                PREFIX=loop_name.upper(),
                kp=loop.pid.kp,
                ki=loop.pid.ki,
                kd=loop.pid.kd,
            ))
        code = "\n".join(parts)

    if args.output:
        output_path = Path(args.output)
        output_path.parent.mkdir(parents=True, exist_ok=True)
        with open(output_path, "w", encoding="utf-8") as f:
            f.write(code)
        print(f"C code written to {output_path}")
    else:
        print(code)


if __name__ == "__main__":
    main()
